version: '3'

services:
  database:
    image: mongo:latest
    
  mongo-seed:
    build: .
    command: npm run seed

  server:
    build: ./
    depends_on:
      - 'database'
    ports: 
      - '3004:3004'
